name: CI

on: [push, pull_request]
  push:
  pull_request:



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.6 for integration-test-docker-environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Run tests
      run: ./run_all_tests.sh
